"use client"
import Link from "next/link"
import {useState} from "react"

type Difficulty="easy"|"normal"|"hard"
type Winner="you"|"bot"|"draw"
const META:Record<string,[string,string]>={tictactoe:["❌⭕","Tic-Tac-Toe"],connect4:["🔴🟡","Connect Four"],rps:["✊✋✌️","Rock Paper Scissors"],reaction:["⚡","Reaction Duel"],"quick-math":["➕","Quick Math Duel"],"button-smash":["🔨","Button Smash"],"target-tap":["🎯","Target Tap"],"coin-duel":["🪙","Coin Duel"],"high-low":["📈","High / Low"],"color-clash":["🎨","Color Clash"]}
const random=<T,>(a:T[])=>a[Math.floor(Math.random()*a.length)]
const winLines=[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]]
function tttWinner(b:string[]){for(const l of winLines)if(b[l[0]]&&b[l[0]]===b[l[1]]&&b[l[1]]===b[l[2]])return b[l[0]] as "you"|"bot";return b.every(Boolean)?"draw":null}
function botTtt(b:string[],d:Difficulty){const e=b.map((v,i)=>v?null:i).filter((x):x is number=>x!==null);if(!e.length)return null;if(d==="easy")return random(e);const find=(m:string)=>e.find(i=>{const n=[...b];n[i]=m;return tttWinner(n)===m});if(d==="hard"){const w=find("bot");if(w!==undefined)return w;const block=find("you");if(block!==undefined)return block;if(b[4]==="")return 4}return random(e)}
export default function BotGame({game}:{game:string}){
 const meta=META[game]||["🎮","Game"];const[d,setD]=useState<Difficulty|null>(null);const[msg,setMsg]=useState("");const[score,setScore]=useState({you:0,bot:0});const[board,setBoard]=useState<string[]>(Array(9).fill(""));const[turn,setTurn]=useState<"you"|"bot">("you");const[math,setMath]=useState(()=>newMath());const[count,setCount]=useState(0);const[target,setTarget]=useState(()=>Math.floor(Math.random()*9));const[choice,setChoice]=useState("");const[number,setNumber]=useState(()=>1+Math.floor(Math.random()*100));const[word,setWord]=useState(()=>random(["RED","BLUE","GREEN","YELLOW"]));const[reaction,setReaction]=useState(false)
 function newMath(){const a=1+Math.floor(Math.random()*12),b=1+Math.floor(Math.random()*12);return{a,b,answer:a+b}}
 function finish(w:Winner){setMsg(w==="you"?"🏆 You win!":w==="bot"?"🤖 Bot wins!":"Draw!");if(w==="you")setScore(s=>({you:s.you+1,bot:s.bot}));if(w==="bot")setScore(s=>({you:s.you,bot:s.bot+1}))}
 function reset(){setMsg("");setBoard(Array(9).fill(""));setTurn("you");setMath(newMath());setCount(0);setTarget(Math.floor(Math.random()*9));setChoice("");setNumber(1+Math.floor(Math.random()*100));setWord(random(["RED","BLUE","GREEN","YELLOW"]));setReaction(false)}
 function choose(x:Difficulty){setD(x);reset();setScore({you:0,bot:0})}
 function move(i:number){if(!d||game!=="tictactoe"||turn!=="you"||board[i]||msg)return;const b=[...board];b[i]="you";const w=tttWinner(b);setBoard(b);if(w){finish(w);return}setTurn("bot");setTimeout(()=>{const bi=botTtt(b,d);if(bi===null)return;const n=[...b];n[bi]="bot";setBoard(n);const bw=tttWinner(n);if(bw)finish(bw);else setTurn("you")},d==="hard"?300:180)}
 function choiceMove(x:string){if(msg||choice)return;setChoice(x);if(game==="rps"){const bot=d==="hard"?({rock:"paper",paper:"scissors",scissors:"rock"} as Record<string,string>)[x]:random(["rock","paper","scissors"]);const w=x===bot?"draw":((x==="rock"&&bot==="scissors")||(x==="paper"&&bot==="rock")||(x==="scissors"&&bot==="paper")?"you":"bot");finish(w as Winner)}else{const bot=d==="hard"?x:random(["heads","tails"]);finish(x===bot?"you":"bot")}}
 function tap(){if(msg)return;const n=count+1;setCount(n);if(n>=10)finish("you");else if(Math.random()<(d==="easy"?.2:d==="normal"?.45:.65)&&n>=9)finish("bot")}
 function targetTap(i:number){if(msg)return;if(i!==target){if(d==="hard"&&Math.random()<.25)finish("bot");return}const n=count+1;setCount(n);if(n>=5)finish("you");else setTarget(Math.floor(Math.random()*9))}
 function mathPick(n:number){if(msg)return;finish(n===math.answer?"you":"bot")}
 function highLow(x:string){if(msg)return;finish(x===(number>=50?"HIGH":"LOW")?"you":"bot")}
 function colorPick(x:string){if(msg)return;finish(x===word?"you":"bot")}
 function reactionStart(){if(msg||reaction)return;setReaction(true);setTimeout(()=>finish("you"),d==="hard"?900:d==="normal"?1300:1700)}
 if(!d)return <main className="min-h-screen bg-gradient-to-br from-purple-950 via-black to-pink-950 p-4 text-white"><div className="mx-auto max-w-xl"><Link href="/games" className="text-sm text-white/60">← Games</Link><div className="mt-5 rounded-3xl border border-white/10 bg-white/5 p-6 text-center"><div className="text-5xl">{meta[0]}</div><h1 className="mt-3 text-2xl font-black">{meta[1]}</h1><p className="mt-2 text-sm text-white/45">Choose bot difficulty.</p><div className="mt-6 grid gap-3"><button onClick={()=>choose("easy")} className="rounded-2xl bg-emerald-500/20 p-4 font-bold">🟢 Easy</button><button onClick={()=>choose("normal")} className="rounded-2xl bg-yellow-500/20 p-4 font-bold">🟡 Normal</button><button onClick={()=>choose("hard")} className="rounded-2xl bg-red-500/20 p-4 font-bold">🔴 Hard</button></div></div></div></main>
 return <main className="min-h-screen bg-gradient-to-br from-purple-950 via-black to-pink-950 p-4 text-white"><div className="mx-auto max-w-xl"><div className="rounded-3xl border border-white/10 bg-white/5 p-5"><div className="flex justify-between"><Link href="/games" className="text-sm text-white/60">← Games</Link><span className="text-xs uppercase text-white/35">{d} bot</span></div><div className="mt-4 text-center"><div className="text-3xl">{meta[0]}</div><h1 className="text-xl font-black">{meta[1]}</h1><div className="mt-2 text-sm text-white/45">You {score.you} · Bot {score.bot}</div></div>{msg&&<div className="mt-4 rounded-2xl bg-pink-500/15 p-3 text-center font-bold">{msg}</div>}
 {game==="tictactoe"&&<div className="mx-auto mt-5 grid max-w-xs grid-cols-3 gap-2">{board.map((v,i)=><button key={i} disabled={!!v||turn!=="you"||!!msg} onClick={()=>move(i)} className="aspect-square rounded-2xl bg-white/10 text-4xl font-black">{v==="you"?"❌":v==="bot"?"⭕":""}</button>)}</div>}
 {game==="connect4"&&<ConnectFour d={d} disabled={!!msg} onWin={finish}/>} 
 {game==="rps"&&<Choice options={[["rock","✊"],["paper","✋"],["scissors","✌️"]]} disabled={!!msg||!!choice} onChoose={choiceMove}/>} 
 {game==="coin-duel"&&<Choice options={[["heads","🪙 Heads"],["tails","🔵 Tails"]]} disabled={!!msg||!!choice} onChoose={choiceMove}/>} 
 {game==="reaction"&&<div className="mt-5"><button disabled={reaction||!!msg} onClick={reactionStart} className="w-full rounded-2xl bg-white/10 py-12 text-2xl font-black">{reaction?"WAIT…":"START"}</button></div>}
 {game==="quick-math"&&<div className="mt-5"><div className="text-center text-4xl font-black">{math.a} + {math.b} = ?</div><div className="mt-4 grid grid-cols-2 gap-2">{[math.answer,math.answer+1,math.answer-1,math.answer+2].map(n=><button key={n} disabled={!!msg} onClick={()=>mathPick(n)} className="rounded-2xl bg-white/10 py-4 text-xl font-bold">{n}</button>)}</div></div>}
 {game==="button-smash"&&<div className="mt-5 text-center"><div>{count}/10</div><button disabled={!!msg} onClick={tap} className="mt-4 h-48 w-48 rounded-full bg-pink-500/25 text-2xl font-black">SMASH!</button></div>}
 {game==="target-tap"&&<div className="mt-5"><div className="text-center">Targets: {count}/5</div><div className="mx-auto mt-4 grid max-w-xs grid-cols-3 gap-2">{Array.from({length:9},(_,i)=><button key={i} disabled={!!msg} onClick={()=>targetTap(i)} className={`aspect-square rounded-2xl ${i===target?"bg-pink-500/50":"bg-white/10"}`}>{i===target?"🎯":""}</button>)}</div></div>}
 {game==="high-low"&&<div className="mt-5 grid grid-cols-2 gap-3">{["HIGH","LOW"].map(x=><button key={x} disabled={!!msg} onClick={()=>highLow(x)} className="rounded-2xl bg-white/10 p-6 text-xl font-black">{x}</button>)}</div>}
 {game==="color-clash"&&<div className="mt-5"><div className="text-center text-4xl font-black">{word}</div><div className="mt-4 grid grid-cols-2 gap-2">{["RED","BLUE","GREEN","YELLOW"].map(x=><button key={x} disabled={!!msg} onClick={()=>colorPick(x)} className="rounded-2xl bg-white/10 py-4 font-bold">{x}</button>)}</div></div>}
 {msg&&<button onClick={reset} className="mt-5 w-full rounded-2xl bg-white/10 py-3 font-semibold">Next Round</button>}
 </div></div></main>
}
function Choice({options,disabled,onChoose}:{options:string[][],disabled:boolean,onChoose:(x:string)=>void}){return <div className="mt-5 grid grid-cols-2 gap-3">{options.map(([x,e])=><button key={x} disabled={disabled} onClick={()=>onChoose(x)} className="rounded-2xl bg-white/10 p-6 text-xl font-bold">{e}</button>)}</div>}
function ConnectFour({d,disabled,onWin}:{d:Difficulty,disabled:boolean,onWin:(w:Winner)=>void}){const[b,setB]=useState<string[]>(Array(42).fill(""));const[t,setT]=useState<"you"|"bot">("you");function check(a:string[]){for(let r=0;r<6;r++)for(let c=0;c<7;c++){const i=r*7+c;if(!a[i])continue;for(const [dr,dc] of [[0,1],[1,0],[1,1],[1,-1]]){const ids=[0,1,2,3].map(k=>{const rr=r+dr*k,cc=c+dc*k;return rr>=0&&rr<6&&cc>=0&&cc<7?rr*7+cc:-1});if(ids.every(x=>x>=0&&a[x]===a[i]))return a[i] as Winner}}return a.every(Boolean)?"draw":null}function drop(c:number,who:"you"|"bot"){if(disabled||t!==who)return;const a=[...b];for(let r=5;r>=0;r--){const i=r*7+c;if(!a[i]){a[i]=who;setB(a);const w=check(a);if(w){onWin(w);return}setT(who==="you"?"bot":"you");if(who==="you")setTimeout(()=>{const cols=Array.from({length:7},(_,x)=>x).filter(x=>!a[x]);if(cols.length)drop(d==="hard"?3:random(cols),"bot")},250);return}}}return <div className="mt-5 grid grid-cols-7 gap-1 rounded-2xl bg-blue-950/40 p-2">{b.map((v,i)=><button key={i} disabled={disabled||t!=="you"||!!v} onClick={()=>drop(i%7,"you")} className="aspect-square rounded-full bg-white/10 text-xl">{v==="you"?"🔴":v==="bot"?"🟡":""}</button>)}</div>}
