"use client"
import Link from "next/link"
import {useState} from "react"

const META:any={pong:["🏓","Pong Duel"],"air-hockey":["🏒","Air Hockey"],penalty:["⚽","Penalty Shootout"],basketball:["🏀","Basketball Duel"],"mini-golf":["⛳","Mini Golf"],memory:["🧠","Memory Match"],"maze-race":["🧩","Maze Race"],"target-range":["🎯","Target Range"],"tower-balance":["🏗️","Tower Balance"],"quick-race":["🏎️","Quick Race"]}
type D="easy"|"normal"|"hard"
const shuffle=(a:any[])=>[...a].sort(()=>Math.random()-.5)
export default function PhaseTwoGame({game}:{game:string}){const meta=META[game]||["🎮","Game"];const[d,setD]=useState<D|null>(null);const[msg,setMsg]=useState("");const[score,setScore]=useState({you:0,bot:0});const[state,setState]=useState<any>(()=>start(game));
function start(g:string){if(g==="memory"){const vals=shuffle([1,1,2,2,3,3,4,4]);return{cards:vals,open:[],matched:[]}}if(g==="maze-race")return{you:0,bot:0};if(g==="tower-balance")return{height:0};if(g==="quick-race")return{you:0,bot:0};return{target:Math.floor(Math.random()*5),shots:0}}
function begin(x:D){setD(x);setMsg("");setScore({you:0,bot:0});setState(start(game))}
function win(w:"you"|"bot"|"draw"){setMsg(w==="draw"?"Draw!":w==="you"?"🏆 You win!":"🤖 Bot wins!");if(w!=="draw")setScore(s=>({...s,[w]:s[w]+1}))}
function next(){setMsg("");setState(start(game))}
if(!d)return <main className="min-h-screen bg-gradient-to-br from-purple-950 via-black to-pink-950 p-4 text-white"><div className="mx-auto max-w-xl"><Link href="/games" className="text-sm text-white/60">← Games</Link><div className="mt-5 rounded-3xl border border-white/10 bg-white/5 p-6 text-center"><div className="text-5xl">{meta[0]}</div><h1 className="mt-3 text-2xl font-black">{meta[1]}</h1><p className="mt-2 text-sm text-white/45">Choose bot difficulty.</p><div className="mt-6 grid gap-3"><button onClick={()=>begin("easy")} className="rounded-2xl bg-emerald-500/20 p-4 font-bold">🟢 Easy</button><button onClick={()=>begin("normal")} className="rounded-2xl bg-yellow-500/20 p-4 font-bold">🟡 Normal</button><button onClick={()=>begin("hard")} className="rounded-2xl bg-red-500/20 p-4 font-bold">🔴 Hard</button></div></div></div></main>
const head=<><div className="flex justify-between"><Link href="/games" className="text-sm text-white/60">← Games</Link><span className="text-xs uppercase text-white/40">{d} bot</span></div><div className="mt-4 text-center"><div className="text-3xl">{meta[0]}</div><h1 className="text-xl font-black">{meta[1]}</h1>{msg&&<div className="mt-3 rounded-2xl bg-pink-500/15 p-3 font-bold">{msg}</div>}</div></>
return <main className="min-h-screen bg-gradient-to-br from-purple-950 via-black to-pink-950 p-4 text-white"><div className="mx-auto max-w-xl"><div className="rounded-3xl border border-white/10 bg-white/5 p-5">{head}
{game==="memory"&&<Memory state={state} setState={setState} msg={msg} win={win}/>} 
{game==="pong"&&<TapRace label="🏓 Keep the rally going" target={12} d={d} msg={msg} onWin={win}/>} 
{game==="air-hockey"&&<TapRace label="🏒 Score 7 goals" target={7} d={d} msg={msg} onWin={win}/>} 
{game==="penalty"&&<Penalty d={d} msg={msg} win={win}/>} 
{game==="basketball"&&<TapRace label="🏀 Make 10 baskets" target={10} d={d} msg={msg} onWin={win}/>} 
{game==="mini-golf"&&<MiniGolf d={d} msg={msg} win={win}/>} 
{game==="maze-race"&&<TapRace label="🧩 Reach the goal" target={8} d={d} msg={msg} onWin={win}/>} 
{game==="target-range"&&<TapRace label="🎯 Hit 8 targets" target={8} d={d} msg={msg} onWin={win}/>} 
{game==="tower-balance"&&<Tower state={state} setState={setState} msg={msg} win={win}/>} 
{game==="quick-race"&&<TapRace label="🏎️ Reach the finish" target={15} d={d} msg={msg} onWin={win}/>} 
{msg&&<button onClick={next} className="mt-5 w-full rounded-2xl bg-white/10 py-3 font-semibold">Next Round</button>}</div></div></main>}
function TapRace({label,target,d,msg,onWin}:{label:string,target:number,d:D,msg:string,onWin:(w:"you"|"bot"|"draw")=>void}){const[p,setP]=useState(0);function tap(){if(msg)return;const n=p+1;setP(n);if(n>=target){onWin("you");return}const chance=d==="easy"?.2:d==="normal"?.45:.65;if(Math.random()<chance&&n+1>=target)onWin("bot")}return <div className="mt-6 text-center"><div className="text-sm text-white/50">{label}</div><div className="mt-3 text-3xl font-black">{p} / {target}</div><button disabled={!!msg} onClick={tap} className="mt-5 w-full rounded-3xl bg-pink-500/25 py-14 text-2xl font-black">PLAY</button></div>}
function Penalty({d,msg,win}:{d:D,msg:string,win:(w:"you"|"bot"|"draw")=>void}){const[shots,setShots]=useState(0);const[goals,setGoals]=useState(0);function kick(side:string){if(msg)return;const keeper=d==="easy"?.25:d==="normal"?.45:.65;const goal=Math.random()>keeper;const ns=shots+1,ng=goals+(goal?1:0);setShots(ns);setGoals(ng);if(ns>=5)win(ng>=3?"you":"bot")}return <div className="mt-6 text-center"><div>{goals} goals · {shots}/5 shots</div><div className="mt-4 grid grid-cols-3 gap-2">{["left","center","right"].map(x=><button key={x} disabled={!!msg} onClick={()=>kick(x)} className="rounded-2xl bg-white/10 p-5">{x}</button>)}</div></div>}
function Memory({state,setState,msg,win}:{state:any,setState:any,msg:string,win:(w:"you"|"bot"|"draw")=>void}){function flip(i:number){if(msg||state.open.includes(i)||state.matched.includes(state.cards[i]))return;const o=[...state.open,i];if(o.length<2){setState({...state,open:o});return}const[a,b]=o;if(state.cards[a]===state.cards[b]){const m=[...state.matched,state.cards[a]];setState({...state,open:[],matched:m});if(m.length===4)win("you")}else setTimeout(()=>setState({...state,open:[]}),500)}return <div className="mt-5 grid grid-cols-4 gap-2">{state.cards.map((v:number,i:number)=><button key={i} onClick={()=>flip(i)} className="aspect-square rounded-2xl bg-white/10 text-2xl">{state.open.includes(i)||state.matched.includes(v)?v:"?"}</button>)}</div>}
function MiniGolf({d,msg,win}:{d:D,msg:string,win:(w:"you"|"bot"|"draw")=>void}){const[strokes,setStrokes]=useState(0);function hit(){if(msg)return;const n=strokes+1;setStrokes(n);if(n>=4)win(n<=4?"you":n===5?"draw":"bot")}return <div className="mt-6 text-center"><div className="text-5xl">⛳</div><p className="mt-3">Strokes: {strokes}</p><button disabled={!!msg} onClick={hit} className="mt-5 w-full rounded-2xl bg-white/10 py-10 text-xl font-black">SWING</button></div>}
function Tower({state,setState,msg,win}:{state:any,setState:any,msg:string,win:(w:"you"|"bot"|"draw")=>void}){function drop(){if(msg)return;const h=state.height+1;setState({height:h});if(Math.random()<(h>6?.2:.1)){win("bot");return}if(h>=10)win("you")}return <div className="mt-6 text-center"><div className="text-6xl">{Array.from({length:state.height},()=>"🧱").join("")||"🏗️"}</div><div className="mt-3">Height: {state.height}/10</div><button disabled={!!msg} onClick={drop} className="mt-5 w-full rounded-2xl bg-white/10 py-10 text-xl font-black">DROP ANIMAL</button></div>}
